import domtoimage from 'dom-to-image-more'
import jsPDF from 'jspdf'
import pptxgen from 'pptxgenjs'

// ─── Shared helper: element → base64 PNG ──────────────────────────────────────

const captureElement = async (elementId, bgColor = '#080f1e') => {
    const element = document.getElementById(elementId)
    if (!element) throw new Error(`Element #${elementId} not found`)
    return domtoimage.toPng(element, {
        bgcolor: bgColor,
        scale: 2,
        style: { borderRadius: '0' },
    })
}

// ─── PowerPoint Export ────────────────────────────────────────────────────────

export const exportAsPowerPoint = async (chartElementId, insights, fileName = 'report') => {
    const pptx = new pptxgen()
    pptx.layout = 'LAYOUT_WIDE'

    // Slide 1: Title
    const slide1 = pptx.addSlide()
    slide1.background = { color: '060817' }
    slide1.addText('Data Analysis Report', {
        x: 0.5, y: 1.5, w: '90%', h: 1.2,
        fontSize: 40, bold: true, color: 'ACBBC6',
        align: 'center', fontFace: 'Arial'
    })
    slide1.addText(fileName, {
        x: 0.5, y: 3, w: '90%', h: 0.6,
        fontSize: 18, color: '667D9D',
        align: 'center', fontFace: 'Arial'
    })
    slide1.addText(`Generated by Vizassistance · ${new Date().toLocaleDateString()}`, {
        x: 0.5, y: 4.2, w: '90%', h: 0.4,
        fontSize: 12, color: '555555',
        align: 'center'
    })

    // Slide 2: Chart
    try {
        const imgData = await captureElement(chartElementId, '#080f1e')
        const slide2 = pptx.addSlide()
        slide2.background = { color: '060817' }
        slide2.addText('Visual Analytics', {
            x: 0.5, y: 0.3, w: '90%', h: 0.5,
            fontSize: 22, bold: true, color: 'ACBBC6'
        })
        slide2.addImage({ data: imgData, x: 0.5, y: 1.0, w: 12, h: 5.5 })
    } catch (e) {
        console.warn('Chart slide skipped:', e)
    }

    // Slides 3+: AI Insights
    if (insights) {
        const sections = insights.split(/\n#{1,3} /).filter(Boolean)
        sections.forEach((section, idx) => {
            const lines = section.split('\n').filter(Boolean)
            const title = lines[0]?.replace(/[#*]/g, '').trim() || `Insight ${idx + 1}`
            const body  = lines.slice(1).join('\n').replace(/[*#`]/g, '').trim()

            const slide = pptx.addSlide()
            slide.background = { color: '060817' }
            slide.addText(title, {
                x: 0.5, y: 0.4, w: '90%', h: 0.7,
                fontSize: 24, bold: true, color: 'ACBBC6', fontFace: 'Arial'
            })
            slide.addShape(pptx.ShapeType.rect, {
                x: 0.5, y: 1.25, w: 12, h: 0.03,
                fill: { color: '16254F' }, line: { color: '16254F' }
            })
            if (body) {
                slide.addText(body.slice(0, 800), {
                    x: 0.5, y: 1.4, w: '90%', h: 4.5,
                    fontSize: 14, color: 'CCCCCC',
                    fontFace: 'Arial', valign: 'top',
                    breakLine: true, wrap: true
                })
            }
            slide.addText(`${idx + 2}`, {
                x: 12.2, y: 6.8, w: 0.5, h: 0.3,
                fontSize: 10, color: '444444', align: 'right'
            })
        })
    }

    await pptx.writeFile({ fileName: `${fileName}.pptx` })
}

// ─── PNG Download ─────────────────────────────────────────────────────────────

export const downloadChartAsPNG = async (elementId, fileName = 'chart.png') => {
    try {
        const dataUrl = await captureElement(elementId, '#080f1e')
        const link = document.createElement('a')
        link.download = fileName
        link.href = dataUrl
        link.click()
    } catch (error) {
        console.error('PNG download failed:', error)
        alert('Failed to download chart. Please try again.')
    }
}

// ─── PDF Export ───────────────────────────────────────────────────────────────

export const exportFullReportAsPDF = async (chartElementId, insightsText, datasetName = 'Dataset') => {
    try {
        const pdf     = new jsPDF('p', 'mm', 'a4')
        const pageW   = pdf.internal.pageSize.getWidth()
        const pageH   = pdf.internal.pageSize.getHeight()
        const margin  = 14
        const contentW = pageW - margin * 2

        // Header
        pdf.setFillColor(22, 37, 79)
        pdf.rect(0, 0, pageW, 28, 'F')
        pdf.setTextColor(255, 255, 255)
        pdf.setFontSize(18)
        pdf.setFont('helvetica', 'bold')
        pdf.text('Vizassistant', margin, 12)
        pdf.setFontSize(10)
        pdf.setFont('helvetica', 'normal')
        pdf.text('AI-Powered Data Analysis Report', margin, 20)
        pdf.setFontSize(8)
        const dateStr = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
        pdf.text(`Dataset: ${datasetName}   |   Generated: ${dateStr}`, margin, 26)

        let cursorY = 36

        // Chart screenshot
        try {
            const imgData = await captureElement(chartElementId, '#080f1e')
            const img = new Image()
            img.src = imgData
            await new Promise(res => { img.onload = res })
            const imgH = (img.naturalHeight * contentW) / img.naturalWidth
            const clampedH = Math.min(imgH, 90)
            pdf.addImage(imgData, 'PNG', margin, cursorY, contentW, clampedH)
            cursorY += clampedH + 8
        } catch (e) {
            console.warn('Chart capture skipped:', e)
        }

        // Divider
        pdf.setDrawColor(200, 200, 200)
        pdf.line(margin, cursorY, pageW - margin, cursorY)
        cursorY += 6

        // AI Insights heading
        pdf.setTextColor(30, 30, 30)
        pdf.setFontSize(13)
        pdf.setFont('helvetica', 'bold')
        pdf.text('AI Strategic Report', margin, cursorY)
        cursorY += 7

        // Insights body
        pdf.setFontSize(9)
        pdf.setFont('helvetica', 'normal')
        pdf.setTextColor(60, 60, 60)

        const cleanText = (insightsText || 'No insights generated yet.')
            .replace(/#{1,6}\s*/g, '')
            .replace(/\*\*(.*?)\*\*/g, '$1')
            .replace(/\*(.*?)\*/g, '$1')
            .replace(/`(.*?)`/g, '$1')
            .replace(/---+/g, '')
            .trim()

        const lines = pdf.splitTextToSize(cleanText, contentW)
        lines.forEach((line) => {
            if (cursorY > pageH - 20) {
                pdf.addPage()
                cursorY = 20
                pdf.setFillColor(22, 37, 79)
                pdf.rect(0, 0, pageW, 10, 'F')
                pdf.setTextColor(255, 255, 255)
                pdf.setFontSize(7)
                pdf.text('Vizassistant — Continued', margin, 7)
                pdf.setTextColor(60, 60, 60)
                pdf.setFontSize(9)
                pdf.setFont('helvetica', 'normal')
            }
            pdf.text(line, margin, cursorY)
            cursorY += 5
        })

        // Footer on all pages
        const totalPages = pdf.internal.getNumberOfPages()
        for (let i = 1; i <= totalPages; i++) {
            pdf.setPage(i)
            pdf.setFontSize(7)
            pdf.setTextColor(160, 160, 160)
            pdf.text(
                `Vizassistant AI Report  |  Page ${i} of ${totalPages}  |  vizassistant.app`,
                margin, pageH - 6
            )
        }

        pdf.save(`${datasetName.replace(/[^a-z0-9]/gi, '_')}_report.pdf`)
    } catch (error) {
        console.error('PDF export failed:', error)
        alert('Failed to export PDF. Please try again.')
    }
}

// ─── CSV Export ───────────────────────────────────────────────────────────────

export const exportDataAsCSV = (data, fileName = 'dataset.csv') => {
    if (!data || data.length === 0) return alert('No data to export.')
    try {
        const headers = Object.keys(data[0])
        const csvRows = [
            headers.join(','),
            ...data.map(row =>
                headers.map(h => {
                    const str = String(row[h] ?? '')
                    return str.includes(',') || str.includes('\n') || str.includes('"')
                        ? `"${str.replace(/"/g, '""')}"`
                        : str
                }).join(',')
            )
        ]
        const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' })
        const link = document.createElement('a')
        link.href = URL.createObjectURL(blob)
        link.download = fileName
        link.click()
        URL.revokeObjectURL(link.href)
    } catch (error) {
        console.error('CSV export failed:', error)
        alert('Failed to export CSV. Please try again.')
    }
}

// ─── TXT Export ───────────────────────────────────────────────────────────────

export const exportInsightsAsTxt = (insightsText, fileName = 'insights.txt') => {
    if (!insightsText) return alert('No insights to export.')
    const blob = new Blob([insightsText], { type: 'text/plain;charset=utf-8;' })
    const link = document.createElement('a')
    link.href = URL.createObjectURL(blob)
    link.download = fileName
    link.click()
    URL.revokeObjectURL(link.href)
}